### ISSUE TITLE
Would you like to upload your code of awd-lstm with fraternal-dropout?

### ISSUE THREAD

**Issue by lirui123456789** [kondiz/fraternal-dropout#2]
Please upload your code of awd-lstm with fraternal-dropout. It would be useful to reproduce your results. Thanks!!!

**Comment by dendisuhubdy** [comment]
@lirui123456789 thank you for your input. You can clone awd-lstm (https://github.com/salesforce/awd-lstm-lm) and ours and then compare the results, thank you.

**Comment by kondiz** [comment]
@lirui123456789 , you may want to check other branches. We already have SOTA results using awd-lstm there. You can find more details in the beginning of the readme :)
